### ISSUE TITLE
Picker won't display when localStorage is not available

### ISSUE THREAD

**Issue by joeattardi** [joeattardi/picmo#184]
Currently trying to show a picker in a browser where localStorage is not available, the following error is thrown:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This needs to be checked and if local storage is not available, recents should not be shown.

**Comment by joeattardi** [comment]
This is fixed in the upcoming 5.0.0 release. Will close the issue upon release.

Also should provide a 4.x fix as well.

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.

**Comment by dEEpProjects** [comment]
This issue is still reproducible using Chrome version 109.0.5414.119 in incognito mode.
~~~
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new jt (https://unpkg.com/picmo@5.7.5/dist/index.js:774:11)
    at Et (https://unpkg.com/picmo@5.7.5/dist/index.js:799:43)
    at Ao (https://unpkg.com/picmo@5.7.5/dist/index.js:1995:13)
    at https://fiddle.jshell.net/p42n1wgv/show/?editor_console=:114:16
~~~

To reproduce it, open the [fiddle](https://jsfiddle.net/p42n1wgv/) in an incognito Chrome.

**Comment by joeattardi** [comment]
Should be fixed for real this time with the just released 5.7.6. I just tried your fiddle but using the newer version, and it seems to be working ok now. Let me know if there's still an issue.
