### ISSUE TITLE
Content Security Policy Issues - BLOCKER

### ISSUE THREAD

**Issue by davecra** [joeattardi/picmo#224]
This library uses inline styles written into the JavaScript for specific emojis, here is snippet from SAD, for example:

```
sad: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
<defs>
<radialGradient gradientUnits="userSpaceOnUse" cy="10%" id="gradient-0">
---> RIGHT HERE --> <stop offset="0" style="stop-color: hsl(50, 100%, 50%);"/>...',
```

Here is the error I get:

![image](https://user-images.githubusercontent.com/19915160/183117530-eb40509a-21a8-4440-917d-8cff73ab22cc.png)

The Content Security Policy for most websites these days BLOCK inline-styles (and inline-code) as a security precaution because they provide an attack vector some malicious code to manipulate the site. Here is a [good answer as to why/how inline styles is bad](https://stackoverflow.com/questions/41925390/what-are-the-risks-associated-with-using-inline-styles#:~:text=A%20Content%20Security%20Policy%20with%20a%20default-src%20or,seems%20to%20indicate%20that%20inline%20styles%20are%20unsafe.).

I was using this library, but it was blocked by the provider, and I have had to remove all references until this is fixed. The solution is to update your code to NOT use inline style or inline JavaScript anywhere in your library. You would need to point to CSS classes in your library for each of these styles or find another way to render these specific items. I do not seem to get any errors for inline JavaScript, but there are 16 instances in the index.js that use inline-styles.

To test this, you can add a (.htaccess) to an APACHE root project that uses your library. Add these two lines to it:

```
Header always set Strict-Transport-Security "max-age=31536000" env=HTTPS
Header add Content-Security-Policy "default-src https:;"
```

Then you will see what I am seeing when you load the page with your library attached. Please let me know if you have any questions about this.

**Comment by joeattardi** [comment]
Hi David, thanks for submitting this, I wasn't aware of CSP issues with PicMo!

The inline styles in are part of the icons. They are SVG icons from Font Awesome. It looks like the inline styles were added by me, to add some color to the icons. 

I will try to look at another solution to styling the SVGs perhaps with an external style sheet (I am not really an expert on SVGs). Worst case I will just remove the styling; avoiding CSP issues is more important to me than colored icons!

Thanks again.

**Comment by joeattardi** [comment]
Luckily there was only one SVG with the inline styles, they have been replaced with plain old CSS inside the SVG.

I just released version 5.4.2 with the fix, hopefully there should be no further CSP issues. Thanks again!

**Comment by davecra** [comment]
I am still getting CSP issues with several of the SVG's used. I copied one to my website "sad.svg" so that you can see the issue:

https://kryl.com/apps/test/sad.svg

When you open that link above first you will see it will not render, the next thing, press F12 and you will see this error:
![image](https://user-images.githubusercontent.com/19915160/183312797-cacb3dfc-a2cb-4d8d-b955-1a23d8eaa47b.png)

The reason is in the SVG itself there is a <style> tag which still counts as inline styles. See this article for more details on making SVG's compliant: [content-security-policy-for-svg-with-inline-style](https://stackoverflow.com/questions/51807182/content-security-policy-for-svg-with-inline-style)

And then this on 'nonce-' for using <style> in the SVG: [CSP Inline Styles](https://content-security-policy.com/examples/allow-inline-style/)

According to the documentation, if you are going to use SVG's with styles you will need to add a 'nonce' value to each one, probably the SAME nonce value to each <style> in each SVG file. I fixed the "sad.svg" by adding a nonce to the style tage like this:

```
  <style nonce="picmo">
    ellipse {
      stroke: #000;
      fill: rgba(0, 0, 0, 0.6);
    }
    #tear {
      fill: #55a7ff;
    }
    #face {
      fill: url(#gradient-0);
    }
  </style>
```

Here is the link to the fixed SAD SVG using nonce:
https://kryl.com/apps/test/sad2.svg

And then in my .HTACCESS file which is required by the vendor to implement STRICT CSP rules, I added this:

> Header add Content-Security-Policy **"style-src https: 'nonce-picmo';"**

To fully make PICMO compliant with inline style CSP you will need to not use styles in your SVG's, not use SVG's in your solution, or put a nonce values in every style you use, then update your documentation to supply that nonce value to developers like me to update our CSP in the .HTACCESS files (or similar for whatever web server we are using - mine is Apache). 

Also... FYI... I am learning about CSP's as we go here as well. This has been a journey for my code as well to get vendor approval for my solution. Let me know if this information helps and if you have any questions about this.

**Comment by joeattardi** [comment]
I finally had a chance to dive deeper into this, looks like there are other CSP violations as you mentioned, these are around the dynamic insertion of CSS styles into the document. The icon I don't care so much about, but looks like these other ones need to be figured out. Will try to make some progress on this this week.

**Comment by joeattardi** [comment]
Ok! I think I have this solved. I removed the inline styles from that SVG file (the easy part). For the errors related to style injection a global config option was added to prevent automatic style injection. Will have an update and hopefully new release soon.

**Comment by joeattardi** [comment]
Circling back on this, I think I have a good solution now. I just released version 5.5.1 which has a refactoring of the CSS. Details are [here](https://picmojs.com/docs/usage/styles) - specifically mentions CSP issues. 

You can disable style injection and add the CSS file manually via a `link` tag or other method. I tested it locally with a strict CSP and it seems to be happy:

```
'Content-Security-Policy': `default-src 'self'; connect-src *; style-src 'self'`
```

I hope this resolves your issue, please let me know if there are other things I missed.

**Comment by davecra** [comment]
Confirmed from my codebase using the new process, it is resolved. 👍 

Thanks, Joe for working on this so quickly! 😄

**Comment by joeattardi** [comment]
No problem! I learned a lot about CSP actually, so it was a win-win!
