### ISSUE TITLE
On the second click, the popup-picker stays at bottom of the container.

### ISSUE THREAD

**Issue by DaniBedz** [joeattardi/picmo#246]
I think I'm running into the same issue previously raised here: https://github.com/joeattardi/picmo/issues/217, that was closed by the reporter.

To recreate, set the `showRecents: false` picker option. When you open the picker the first time, it will display the 'smileys and emotions' category, at the top of the container. If you close and reopen the picker, the container's focus is at the bottom of the container, so you see the flags:

![2022-09-29 12 37 05](https://user-images.githubusercontent.com/49581958/192925976-f2d92d0f-bca6-4e4d-9758-e7cfcf670a56.gif)

Storybook also doesn't see to respect the value of the checkbox for this UI element, so I don't know if it can be reproduced in storybook alone at the moment:
![2022-09-29 12 34 44](https://user-images.githubusercontent.com/49581958/192925701-06571949-ed5e-418a-9d62-4036bffe472c.png)

I tried to set the `initialEmoji` and `initialCategory`, to the first emoji, but that didn't resolve the issue.

Just let me know if you need any more info.

Thanks for the great project!

**Comment by joeattardi** [comment]
I just released 5.7.1 which should resolve this issue!

**Comment by DaniBedz** [comment]
Uh oh, looks like it's still happening on 5.7.1 if `showRecents: false` is set.

**Comment by joeattardi** [comment]
Reopening for now. I fixed the Storybook demo, so it now respects the flags in the popup picker. I can't seem to reproduce the behavior now - can you maybe put together a codepen or similar showing the issue? Maybe I am missing a scenario.

**Comment by joeattardi** [comment]
@DaniBedz Can you provide a reproducible example?

**Comment by tuannm151** [comment]
I had the same issue when using css `display: none` to toggle the visibility for the picker. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67471828/201654166-f132c1cc-31ab-4ea5-9461-eeaaa265bbf6.gif)

**Comment by joeattardi** [comment]
@tuannm151 I can't tell for sure from your GIF but it looks like this is the core picker package, is that right? I haven't been able to reproduce this - I loaded it in https://picmojs.com/storybook/, selected the picker element, and toggled `display: none` as you have shown here - the scroll position did not change.

Can you provide a quick codepen or similar example showing the problem and let me know the browser you're using? Thanks.

**Comment by joeattardi** [comment]
@tuannm151 Just following up with you, if you can create an example showcasing the issue I'd be happy to look into it deeper

**Comment by dEEpProjects** [comment]
> @tuannm151 I can't tell for sure from your GIF but it looks like this is the core picker package, is that right? I haven't been able to reproduce this - I loaded it in https://picmojs.com/storybook/, selected the picker element, and toggled `display: none` as you have shown here - the scroll position did not change.
> 
> Can you provide a quick codepen or similar example showing the problem and let me know the browser you're using? Thanks.

I have the same issue and I can reproduce it in the storybook when the recents category is selected. On my project, instead, it happens with any category.

**Comment by joeattardi** [comment]
I can reproduce this now with the base (non-popup) picker. If I scroll up to select the recents category, and I apply `display: none` to the picker then remove it, it jumps to the last category. Or, if I disable the recents category, it happens with the first category.

Is this what you are referring to? Based on the description and GIFs above, it seems to be. I will take a look.

**Comment by joeattardi** [comment]
Finally found the cause for this! I think I have a proper fix, will hopefully have a new release out this week to address this.

Thanks for the additional details.

**Comment by joeattardi** [comment]
Just published a new release, 5.7.3, that should resolve this issue. Please let me know or reopen if you still have issues!
